window.__APP_IMPORTED_DATA = {
  "version": "2026-07-09T16:16:31.844826",
  "influencers": [
    {
      "id": "influencer-1",
      "platform": "Instagram",
      "accountHandle": "@mengmengliving",
      "displayName": "Mengmeng Living",
      "profileUrl": "https://www.instagram.com/mengmengliving",
      "country": "待确认，疑似欧洲/匈牙利",
      "followerCount": 42000,
      "followerTier": "Micro",
      "contentType": "Interior / Lifestyle / UGC / Product photography",
      "bioKeywords": "Interior • Lifestyle；UGC & Product photography；DM for collabs & inquiries",
      "avatarUrl": "",
      "autoFillStatus": "来自 Excel 导入",
      "fitReason": "审美与 pretty / romantic bedding 匹配；更适合做 UGC、产品摄影和卧室氛围图。",
      "recommendedProducts": "Floral duvet cover；pretty bedding；quilt；cottage bedding",
      "contactInfo": "待确认",
      "priority": "A-",
      "status": "未联系",
      "isContacted": false,
      "firstContactChannel": "DM；如主页有邮箱优先邮箱",
      "quoteAmount": "",
      "notes": "先确认受众国家与寄样可达性。",
      "isSelectedForReport": false,
      "isDeleted": false,
      "deletedAt": "",
      "deletionReason": "",
      "images": [],
      "logs": [
        {
          "id": "influencer-1-log-import",
          "actionType": "导入",
          "actionNote": "从 Excel 导入达人主档案",
          "actionDate": "2026-07-09T16:16:31.844826"
        }
      ],
      "createdAt": "2026-07-09T16:16:31.844826",
      "updatedAt": "2026-07-09T16:16:31.844826"
    },
    {
      "id": "influencer-2",
      "platform": "Instagram",
      "accountHandle": "@shegaveitago",
      "displayName": "Brendt Blanks",
      "profileUrl": "https://www.instagram.com/shegaveitago",
      "country": "美国可能性高，待确认",
      "followerCount": 344000,
      "followerTier": "Macro",
      "contentType": "Cozy home / Everyday fashion / Amazon finds",
      "bioKeywords": "Cozy Home + Everyday Fashion；Curated Amazon finds；Author",
      "avatarUrl": "",
      "autoFillStatus": "来自 Excel 导入",
      "fitReason": "Amazon finds 属性强，适合带货/折扣码；粉丝量大，报价可能较高。",
      "recommendedProducts": "Amazon 在售 bedding；quilt；duvet cover；seasonal bedroom looks",
      "contactInfo": "待确认",
      "priority": "A-",
      "status": "未联系",
      "isContacted": false,
      "firstContactChannel": "邮箱或 DM",
      "quoteAmount": "",
      "notes": "建议先询价，不作为低成本寄样首选。",
      "isSelectedForReport": false,
      "isDeleted": false,
      "deletedAt": "",
      "deletionReason": "",
      "images": [],
      "logs": [
        {
          "id": "influencer-2-log-import",
          "actionType": "导入",
          "actionNote": "从 Excel 导入达人主档案",
          "actionDate": "2026-07-09T16:16:31.844826"
        }
      ],
      "createdAt": "2026-07-09T16:16:31.844826",
      "updatedAt": "2026-07-09T16:16:31.844826"
    },
    {
      "id": "influencer-3",
      "platform": "Instagram",
      "accountHandle": "@thislovelyabode",
      "displayName": "Erika Diaz | Home Decor + Design",
      "profileUrl": "https://www.instagram.com/thislovelyabode",
      "country": "美国 MD 可能性高，待确认",
      "followerCount": 63000,
      "followerTier": "Mid-tier",
      "contentType": "Affordable home decor / Design / Daily deals",
      "bioKeywords": "Affordable Home Decor；Intentional Design；Splurge Worthy Finds；Daily Deals",
      "avatarUrl": "",
      "autoFillStatus": "来自 Excel 导入",
      "fitReason": "家居装饰和 deals 属性明显，可能适合折扣码与独立站/亚马逊转化。",
      "recommendedProducts": "Affordable bedding；duvet cover；quilt；bedroom refresh",
      "contactInfo": "待确认",
      "priority": "A",
      "status": "未联系",
      "isContacted": false,
      "firstContactChannel": "邮箱或 DM",
      "quoteAmount": "",
      "notes": "检查近期 Reels 播放量和是否经常发卧室。",
      "isSelectedForReport": false,
      "isDeleted": false,
      "deletedAt": "",
      "deletionReason": "",
      "images": [],
      "logs": [
        {
          "id": "influencer-3-log-import",
          "actionType": "导入",
          "actionNote": "从 Excel 导入达人主档案",
          "actionDate": "2026-07-09T16:16:31.844826"
        }
      ],
      "createdAt": "2026-07-09T16:16:31.844826",
      "updatedAt": "2026-07-09T16:16:31.844826"
    },
    {
      "id": "influencer-4",
      "platform": "Instagram",
      "accountHandle": "@farmtotablecreations",
      "displayName": "Kelly Bontrager",
      "profileUrl": "https://www.instagram.com/farmtotablecreations",
      "country": "Michigan, USA；也出现 Atlanta, GA 信息，待确认",
      "followerCount": 526000,
      "followerTier": "Macro",
      "contentType": "Home decor / DIY / Seasonal styling",
      "bioKeywords": "Creator；Mixer of Styles；Holiday Home Decor；DIY；home decorating ideas；cozy home；home refresh",
      "avatarUrl": "",
      "autoFillStatus": "来自 Excel 导入",
      "fitReason": "体量大、家居/节日布置强；适合 seasonal bedroom 或 holiday home 场景，但报价可能高。",
      "recommendedProducts": "Quilt；floral bedding；holiday bedroom；farmhouse bedding",
      "contactInfo": "待确认",
      "priority": "B+",
      "status": "未联系",
      "isContacted": false,
      "firstContactChannel": "邮箱或 DM",
      "quoteAmount": "",
      "notes": "先作为中后期付费合作候选，确认报价。",
      "isSelectedForReport": false,
      "isDeleted": false,
      "deletedAt": "",
      "deletionReason": "",
      "images": [],
      "logs": [
        {
          "id": "influencer-4-log-import",
          "actionType": "导入",
          "actionNote": "从 Excel 导入达人主档案",
          "actionDate": "2026-07-09T16:16:31.844826"
        }
      ],
      "createdAt": "2026-07-09T16:16:31.844826",
      "updatedAt": "2026-07-09T16:16:31.844826"
    },
    {
      "id": "influencer-5",
      "platform": "Instagram",
      "accountHandle": "@ahomeofhappiness",
      "displayName": "Jilmil / Jil",
      "profileUrl": "https://www.instagram.com/ahomeofhappiness",
      "country": "待确认",
      "followerCount": 50000,
      "followerTier": "Mid-tier",
      "contentType": "Home decor / Relatable content / Tips & inspo",
      "bioKeywords": "Home decor enthusiast；Relatable content to elevate your space；Tips, inspo & brand content",
      "avatarUrl": "",
      "autoFillStatus": "来自 Excel 导入",
      "fitReason": "粉丝量适中，home decor 定位清晰；适合第一批询价/寄样测试。",
      "recommendedProducts": "Pretty bedding；quilt；duvet cover；bedroom styling",
      "contactInfo": "待确认",
      "priority": "A",
      "status": "未联系",
      "isContacted": false,
      "firstContactChannel": "DM；如主页有邮箱优先邮箱",
      "quoteAmount": "",
      "notes": "优先确认卧室内容占比和受众地区。",
      "isSelectedForReport": false,
      "isDeleted": false,
      "deletedAt": "",
      "deletionReason": "",
      "images": [],
      "logs": [
        {
          "id": "influencer-5-log-import",
          "actionType": "导入",
          "actionNote": "从 Excel 导入达人主档案",
          "actionDate": "2026-07-09T16:16:31.844826"
        }
      ],
      "createdAt": "2026-07-09T16:16:31.844826",
      "updatedAt": "2026-07-09T16:16:31.844826"
    },
    {
      "id": "influencer-6",
      "platform": "Instagram",
      "accountHandle": "@ashleylynhome",
      "displayName": "Ashley | Home & Garden Decor",
      "profileUrl": "https://www.instagram.com/ashleylynhome",
      "country": "待确认",
      "followerCount": 152000,
      "followerTier": "Macro",
      "contentType": "Home & garden decor / Cozy lived-in home",
      "bioKeywords": "Helping you create a cozy, lived-in home；Work with me",
      "avatarUrl": "",
      "autoFillStatus": "来自 Excel 导入",
      "fitReason": "家居风格成熟，cozy/lived-in 与 Brandream 部分产品匹配；有公开合作邮箱。",
      "recommendedProducts": "Quilt；floral duvet cover；farmhouse / cottage bedding",
      "contactInfo": "collabs@ashleylynhome.com",
      "priority": "A-",
      "status": "未联系",
      "isContacted": false,
      "firstContactChannel": "Email",
      "quoteAmount": "",
      "notes": "先发邮件询价；适合中期合作。",
      "isSelectedForReport": false,
      "isDeleted": false,
      "deletedAt": "",
      "deletionReason": "",
      "images": [],
      "logs": [
        {
          "id": "influencer-6-log-import",
          "actionType": "导入",
          "actionNote": "从 Excel 导入达人主档案",
          "actionDate": "2026-07-09T16:16:31.844826"
        }
      ],
      "createdAt": "2026-07-09T16:16:31.844826",
      "updatedAt": "2026-07-09T16:16:31.844826"
    },
    {
      "id": "influencer-7",
      "platform": "Instagram",
      "accountHandle": "@beigelove.r",
      "displayName": "UGC • Content Creator • aesthetic soul",
      "profileUrl": "https://www.instagram.com/beigelove.r",
      "country": "待确认",
      "followerCount": 21000,
      "followerTier": "Micro",
      "contentType": "UGC / Home decor / Beige tones",
      "bioKeywords": "UGC；Content Creator；home decor；home accessories；beige tones",
      "avatarUrl": "",
      "autoFillStatus": "来自 Excel 导入",
      "fitReason": "粉丝不算大但 UGC 属性强，适合低成本素材测试；更偏 beige/neutral。",
      "recommendedProducts": "Neutral bedding；cream / beige quilt；soft bedroom styling",
      "contactInfo": "待确认",
      "priority": "A",
      "status": "未联系",
      "isContacted": false,
      "firstContactChannel": "DM",
      "quoteAmount": "",
      "notes": "适合素材产出，不一定强带货。",
      "isSelectedForReport": false,
      "isDeleted": false,
      "deletedAt": "",
      "deletionReason": "",
      "images": [],
      "logs": [
        {
          "id": "influencer-7-log-import",
          "actionType": "导入",
          "actionNote": "从 Excel 导入达人主档案",
          "actionDate": "2026-07-09T16:16:31.844826"
        }
      ],
      "createdAt": "2026-07-09T16:16:31.844826",
      "updatedAt": "2026-07-09T16:16:31.844826"
    },
    {
      "id": "influencer-8",
      "platform": "Instagram",
      "accountHandle": "@flowbylara",
      "displayName": "Flow by Lara",
      "profileUrl": "https://www.instagram.com/flowbylara",
      "country": "待确认",
      "followerCount": 268000,
      "followerTier": "Macro",
      "contentType": "Boho interiors / Soulful living / Styling tips",
      "bioKeywords": "Spaces that tell stories；Tips & tricks to style with soul；Boho interiors & soulful living；Culture, Nature, Warmth",
      "avatarUrl": "",
      "autoFillStatus": "来自 Excel 导入",
      "fitReason": "账号偏 boho / soulful interiors，适合 Brandream 的 boho、warm bedroom 方向；与粉色法式线不完全一致。",
      "recommendedProducts": "Boho bedding；warm neutral quilt；green/sage bedding；bedroom corner",
      "contactInfo": "待确认",
      "priority": "B+",
      "status": "未联系",
      "isContacted": false,
      "firstContactChannel": "DM；如主页有邮箱优先邮箱",
      "quoteAmount": "",
      "notes": "如果要做 boho 板块可优先；普通 romantic bedding 优先级下降。",
      "isSelectedForReport": false,
      "isDeleted": false,
      "deletedAt": "",
      "deletionReason": "",
      "images": [],
      "logs": [
        {
          "id": "influencer-8-log-import",
          "actionType": "导入",
          "actionNote": "从 Excel 导入达人主档案",
          "actionDate": "2026-07-09T16:16:31.844826"
        }
      ],
      "createdAt": "2026-07-09T16:16:31.844826",
      "updatedAt": "2026-07-09T16:16:31.844826"
    },
    {
      "id": "influencer-9",
      "platform": "Instagram",
      "accountHandle": "@nordwind.hygge",
      "displayName": "Anna Konetz",
      "profileUrl": "https://www.instagram.com/nordwind.hygge",
      "country": "Germany / UAE",
      "followerCount": 382000,
      "followerTier": "Macro",
      "contentType": "Interior / Home decor / Hygge / Comfy vibes",
      "bioKeywords": "interior • home decor • comfy vibes；Germany/UAE；Shop my home",
      "avatarUrl": "",
      "autoFillStatus": "来自 Excel 导入",
      "fitReason": "卧室和 bedding 场景潜力强；但受众和寄样地区可能偏欧洲/中东，需确认销售市场匹配。",
      "recommendedProducts": "Matelassé bedding；neutral quilt；hygge bedroom；cozy bedding",
      "contactInfo": "nordwind.hygge@gmail.com",
      "priority": "B+",
      "status": "未联系",
      "isContacted": false,
      "firstContactChannel": "Email / DM",
      "quoteAmount": "",
      "notes": "确认受众国家，美国转化可能有限。",
      "isSelectedForReport": false,
      "isDeleted": false,
      "deletedAt": "",
      "deletionReason": "",
      "images": [],
      "logs": [
        {
          "id": "influencer-9-log-import",
          "actionType": "导入",
          "actionNote": "从 Excel 导入达人主档案",
          "actionDate": "2026-07-09T16:16:31.844826"
        }
      ],
      "createdAt": "2026-07-09T16:16:31.844826",
      "updatedAt": "2026-07-09T16:16:31.844826"
    },
    {
      "id": "influencer-10",
      "platform": "Instagram",
      "accountHandle": "@thecottagejournal",
      "displayName": "The Cottage Journal",
      "profileUrl": "https://www.instagram.com/thecottagejournal",
      "country": "Birmingham, AL, USA",
      "followerCount": 451000,
      "followerTier": "Macro / Media",
      "contentType": "Magazine / Cottage living / Interiors / Gardens",
      "bioKeywords": "Official Instagram of The Cottage Journal magazine；daily inspiration for cottage living, interiors, and gardens",
      "avatarUrl": "",
      "autoFillStatus": "来自 Excel 导入",
      "fitReason": "非常匹配 cottage 审美，但这是媒体账号，不是普通达人；更适合 PR/广告/编辑合作。",
      "recommendedProducts": "Cottage bedding；floral duvet cover；romantic quilt；brand story",
      "contactInfo": "待确认",
      "priority": "B",
      "status": "未联系",
      "isContacted": false,
      "firstContactChannel": "官网/媒体邮箱/DM",
      "quoteAmount": "",
      "notes": "不建议第一批寄样达人；可做品牌曝光和媒体资源。",
      "isSelectedForReport": false,
      "isDeleted": false,
      "deletedAt": "",
      "deletionReason": "",
      "images": [],
      "logs": [
        {
          "id": "influencer-10-log-import",
          "actionType": "导入",
          "actionNote": "从 Excel 导入达人主档案",
          "actionDate": "2026-07-09T16:16:31.844826"
        }
      ],
      "createdAt": "2026-07-09T16:16:31.844826",
      "updatedAt": "2026-07-09T16:16:31.844826"
    },
    {
      "id": "influencer-11",
      "platform": "Instagram",
      "accountHandle": "@thegeorgianwhitepoppy",
      "displayName": "The Georgian White Poppy",
      "profileUrl": "https://www.instagram.com/thegeorgianwhitepoppy",
      "country": "英国可能性高，待确认",
      "followerCount": 51000,
      "followerTier": "Mid-tier",
      "contentType": "English cottage style / Vintage + new cozy home",
      "bioKeywords": "English cottage style；Curate vintage+new=cozy home；Published",
      "avatarUrl": "",
      "autoFillStatus": "来自 Excel 导入",
      "fitReason": "English cottage 风格高度匹配 Brandream romantic/cottage 产品。",
      "recommendedProducts": "Floral duvet cover；lace bed skirt；quilt；French country bedding",
      "contactInfo": "待确认",
      "priority": "A",
      "status": "未联系",
      "isContacted": false,
      "firstContactChannel": "DM；如主页有邮箱优先邮箱",
      "quoteAmount": "",
      "notes": "确认是否可寄样、是否有美国受众。",
      "isSelectedForReport": false,
      "isDeleted": false,
      "deletedAt": "",
      "deletionReason": "",
      "images": [],
      "logs": [
        {
          "id": "influencer-11-log-import",
          "actionType": "导入",
          "actionNote": "从 Excel 导入达人主档案",
          "actionDate": "2026-07-09T16:16:31.844826"
        }
      ],
      "createdAt": "2026-07-09T16:16:31.844826",
      "updatedAt": "2026-07-09T16:16:31.844826"
    },
    {
      "id": "influencer-12",
      "platform": "Instagram",
      "accountHandle": "@oaktreehome",
      "displayName": "English Country Home & Seasonal Styling",
      "profileUrl": "https://www.instagram.com/oaktreehome",
      "country": "Northern England",
      "followerCount": 153000,
      "followerTier": "Macro",
      "contentType": "English country home / Seasonal styling / Eclectic interiors",
      "bioKeywords": "Curating our home through the seasons；Eclectic interiors & crafted creations；Northern England",
      "avatarUrl": "",
      "autoFillStatus": "来自 Excel 导入",
      "fitReason": "English country / seasonal 与 Brandream floral、cottage 产品贴合，但地区偏 UK。",
      "recommendedProducts": "Cottage bedding；floral quilt；seasonal bedroom；bed skirt",
      "contactInfo": "待确认",
      "priority": "B+",
      "status": "未联系",
      "isContacted": false,
      "firstContactChannel": "DM；如主页有邮箱优先邮箱",
      "quoteAmount": "",
      "notes": "适合做品牌调性，不一定第一批转化。",
      "isSelectedForReport": false,
      "isDeleted": false,
      "deletedAt": "",
      "deletionReason": "",
      "images": [],
      "logs": [
        {
          "id": "influencer-12-log-import",
          "actionType": "导入",
          "actionNote": "从 Excel 导入达人主档案",
          "actionDate": "2026-07-09T16:16:31.844826"
        }
      ],
      "createdAt": "2026-07-09T16:16:31.844826",
      "updatedAt": "2026-07-09T16:16:31.844826"
    },
    {
      "id": "influencer-13",
      "platform": "Instagram",
      "accountHandle": "@stayinginstudio",
      "displayName": "Kirsty Tallowin",
      "profileUrl": "https://www.instagram.com/stayinginstudio",
      "country": "英国可能性高，待确认",
      "followerCount": 57000,
      "followerTier": "Mid-tier",
      "contentType": "Countryside / Slow living / Cosy homeware",
      "bioKeywords": "Daydreamer living in the countryside；Cosy homeware for slow living；shop below",
      "avatarUrl": "",
      "autoFillStatus": "来自 Excel 导入",
      "fitReason": "风格温柔、慢生活，很适合 Brandream 的 cottage/romantic 线；但可能自营 homeware。",
      "recommendedProducts": "Floral bedding；lace bed skirt；quilt；soft romantic bedroom",
      "contactInfo": "待确认",
      "priority": "A-",
      "status": "未联系",
      "isContacted": false,
      "firstContactChannel": "DM；如主页有邮箱优先邮箱",
      "quoteAmount": "",
      "notes": "确认是否接受其他品牌家纺合作。",
      "isSelectedForReport": false,
      "isDeleted": false,
      "deletedAt": "",
      "deletionReason": "",
      "images": [],
      "logs": [
        {
          "id": "influencer-13-log-import",
          "actionType": "导入",
          "actionNote": "从 Excel 导入达人主档案",
          "actionDate": "2026-07-09T16:16:31.844826"
        }
      ],
      "createdAt": "2026-07-09T16:16:31.844826",
      "updatedAt": "2026-07-09T16:16:31.844826"
    },
    {
      "id": "influencer-14",
      "platform": "Instagram",
      "accountHandle": "@ourlittleflintcottage",
      "displayName": "Jessie ~ Country Cottage Living",
      "profileUrl": "https://www.instagram.com/ourlittleflintcottage",
      "country": "英国可能性高，待确认",
      "followerCount": 100000,
      "followerTier": "Mid-tier",
      "contentType": "Country cottage living / Rustic interiors / Renovation",
      "bioKeywords": "Calm Rustic Interiors；Interior Styling；Vintage Finds；Renovating 200 year old Flint cottage",
      "avatarUrl": "",
      "autoFillStatus": "来自 Excel 导入",
      "fitReason": "cottage/rustic 与 Brandream 一致，适合产品布置图；粉丝量中高。",
      "recommendedProducts": "Cottage bedding；quilt；floral duvet cover；vintage-style bedding",
      "contactInfo": "待确认",
      "priority": "A-",
      "status": "未联系",
      "isContacted": false,
      "firstContactChannel": "DM；如主页有邮箱优先邮箱",
      "quoteAmount": "",
      "notes": "确认报价和卧室内容比例。",
      "isSelectedForReport": false,
      "isDeleted": false,
      "deletedAt": "",
      "deletionReason": "",
      "images": [],
      "logs": [
        {
          "id": "influencer-14-log-import",
          "actionType": "导入",
          "actionNote": "从 Excel 导入达人主档案",
          "actionDate": "2026-07-09T16:16:31.844826"
        }
      ],
      "createdAt": "2026-07-09T16:16:31.844826",
      "updatedAt": "2026-07-09T16:16:31.844826"
    },
    {
      "id": "influencer-15",
      "platform": "Instagram",
      "accountHandle": "@haresandhome",
      "displayName": "Yvette Marsh",
      "profileUrl": "https://www.instagram.com/haresandhome",
      "country": "待确认",
      "followerCount": 34000,
      "followerTier": "Micro",
      "contentType": "Interiors / Vintage finds / Painted furniture / Maileg",
      "bioKeywords": "Lover of interiors, vintage finds, painted furniture and Maileg",
      "avatarUrl": "",
      "autoFillStatus": "来自 Excel 导入",
      "fitReason": "体量适中，vintage/cottage 味道强；适合寄样测试，但带货能力需观察。",
      "recommendedProducts": "Lace bed skirt；vintage quilt；floral bedding；cottage bedroom props",
      "contactInfo": "待确认",
      "priority": "A-",
      "status": "未联系",
      "isContacted": false,
      "firstContactChannel": "DM；如主页有邮箱优先邮箱",
      "quoteAmount": "",
      "notes": "适合小预算测试。",
      "isSelectedForReport": false,
      "isDeleted": false,
      "deletedAt": "",
      "deletionReason": "",
      "images": [],
      "logs": [
        {
          "id": "influencer-15-log-import",
          "actionType": "导入",
          "actionNote": "从 Excel 导入达人主档案",
          "actionDate": "2026-07-09T16:16:31.844826"
        }
      ],
      "createdAt": "2026-07-09T16:16:31.844826",
      "updatedAt": "2026-07-09T16:16:31.844826"
    },
    {
      "id": "influencer-16",
      "platform": "Instagram",
      "accountHandle": "@coryell.home",
      "displayName": "Melissa Coryell | Coryell Home",
      "profileUrl": "https://www.instagram.com/coryell.home",
      "country": "待确认",
      "followerCount": 292000,
      "followerTier": "Macro",
      "contentType": "Pretty & practical home / Thoughtful styling",
      "bioKeywords": "For homebodies who crave pretty and practical；Thoughtful styling for a warming and charming home",
      "avatarUrl": "",
      "autoFillStatus": "来自 Excel 导入",
      "fitReason": "账号定位里有 pretty/practical，与 Brandream 的漂亮+舒适非常接近；粉丝较大。",
      "recommendedProducts": "Pretty bedding；quilt；floral duvet cover；bedroom refresh",
      "contactInfo": "待确认",
      "priority": "A-",
      "status": "未联系",
      "isContacted": false,
      "firstContactChannel": "DM；如主页有邮箱优先邮箱",
      "quoteAmount": "",
      "notes": "很匹配，但费用可能高；可先询价。",
      "isSelectedForReport": false,
      "isDeleted": false,
      "deletedAt": "",
      "deletionReason": "",
      "images": [],
      "logs": [
        {
          "id": "influencer-16-log-import",
          "actionType": "导入",
          "actionNote": "从 Excel 导入达人主档案",
          "actionDate": "2026-07-09T16:16:31.844826"
        }
      ],
      "createdAt": "2026-07-09T16:16:31.844826",
      "updatedAt": "2026-07-09T16:16:31.844826"
    },
    {
      "id": "influencer-17",
      "platform": "Instagram",
      "accountHandle": "@homeonthehey",
      "displayName": "Alice | Classic Interiors",
      "profileUrl": "https://www.instagram.com/homeonthehey",
      "country": "英国可能性高，待确认",
      "followerCount": 499000,
      "followerTier": "Macro",
      "contentType": "Classic interiors / English home renovation / Seasonal styling",
      "bioKeywords": "Renovating my English 1930s home；cosy moments at home；styling the seasons",
      "avatarUrl": "",
      "autoFillStatus": "来自 Excel 导入",
      "fitReason": "classic interiors 与 cottage bedding 很配；粉丝大且有公开合作邮箱。",
      "recommendedProducts": "Classic floral bedding；quilt；cottage bedding；seasonal bedroom",
      "contactInfo": "homeonthehey@gmail.com",
      "priority": "B+",
      "status": "未联系",
      "isContacted": false,
      "firstContactChannel": "Email",
      "quoteAmount": "",
      "notes": "适合中后期预算合作，先询价。",
      "isSelectedForReport": false,
      "isDeleted": false,
      "deletedAt": "",
      "deletionReason": "",
      "images": [],
      "logs": [
        {
          "id": "influencer-17-log-import",
          "actionType": "导入",
          "actionNote": "从 Excel 导入达人主档案",
          "actionDate": "2026-07-09T16:16:31.844826"
        }
      ],
      "createdAt": "2026-07-09T16:16:31.844826",
      "updatedAt": "2026-07-09T16:16:31.844826"
    },
    {
      "id": "influencer-18",
      "platform": "Instagram",
      "accountHandle": "@cosylittlehaven",
      "displayName": "Sharon",
      "profileUrl": "https://www.instagram.com/cosylittlehaven",
      "country": "英国可能性高，待确认",
      "followerCount": 56000,
      "followerTier": "Mid-tier",
      "contentType": "English cosy cottage style / Slow living / Pets / Seasonal beauty",
      "bioKeywords": "English Cosy Cottage Style；Slow Living, Pets & Seasonal Beauty；100 year old cosy country home",
      "avatarUrl": "",
      "autoFillStatus": "来自 Excel 导入",
      "fitReason": "小而精准的 cottage/slow living 账号，适合 Brandream romantic/cottage 风格第一批测试。",
      "recommendedProducts": "Floral duvet cover；lace bed skirt；quilt；romantic cottage bedding",
      "contactInfo": "Sharonbetts80@icloud.com",
      "priority": "A",
      "status": "未联系",
      "isContacted": false,
      "firstContactChannel": "Email / DM",
      "quoteAmount": "",
      "notes": "可优先联系，确认报价和寄样地址。",
      "isSelectedForReport": false,
      "isDeleted": false,
      "deletedAt": "",
      "deletionReason": "",
      "images": [],
      "logs": [
        {
          "id": "influencer-18-log-import",
          "actionType": "导入",
          "actionNote": "从 Excel 导入达人主档案",
          "actionDate": "2026-07-09T16:16:31.844826"
        }
      ],
      "createdAt": "2026-07-09T16:16:31.844826",
      "updatedAt": "2026-07-09T16:16:31.844826"
    },
    {
      "id": "influencer-19",
      "platform": "Instagram",
      "accountHandle": "@elle_the_home_bird",
      "displayName": "Elle Hervin",
      "profileUrl": "https://www.instagram.com/elle_the_home_bird",
      "country": "待确认，英国可能性高",
      "followerCount": 1000000,
      "followerTier": "Mega",
      "contentType": "Vintage interiors / Content creator / Journalist / Author",
      "bioKeywords": "Journalist；Author；Vintage Interiors；Content Creator；home décor, bookshelves, whimsical décor",
      "avatarUrl": "",
      "autoFillStatus": "来自 Excel 导入",
      "fitReason": "审美强、曝光大，但体量过大；不适合第一批低成本寄样，适合品牌曝光预算。",
      "recommendedProducts": "Statement bedding；vintage floral bedroom；brand awareness campaign",
      "contactInfo": "待确认",
      "priority": "C+",
      "status": "未联系",
      "isContacted": false,
      "firstContactChannel": "邮箱或 DM",
      "quoteAmount": "",
      "notes": "先放观察池；没有预算不建议优先联系。",
      "isSelectedForReport": false,
      "isDeleted": false,
      "deletedAt": "",
      "deletionReason": "",
      "images": [],
      "logs": [
        {
          "id": "influencer-19-log-import",
          "actionType": "导入",
          "actionNote": "从 Excel 导入达人主档案",
          "actionDate": "2026-07-09T16:16:31.844826"
        }
      ],
      "createdAt": "2026-07-09T16:16:31.844826",
      "updatedAt": "2026-07-09T16:16:31.844826"
    },
    {
      "id": "influencer-20",
      "platform": "Instagram",
      "accountHandle": "@villagelittleinteriors",
      "displayName": "Village Little Interiors",
      "profileUrl": "https://www.instagram.com/villagelittleinteriors",
      "country": "Western Australia, Australia",
      "followerCount": 15000,
      "followerTier": "Micro",
      "contentType": "Furniture brand / English-country children’s interiors / Romantic bedrooms",
      "bioKeywords": "Romanticise the everyday；heirloom furniture inspired by English countryside living；handcrafted vintage-inspired beds",
      "avatarUrl": "",
      "autoFillStatus": "来自 Excel 导入",
      "fitReason": "风格与 Brandream 的 cottage、romantic、儿童房床品高度匹配；但它是家具品牌而非传统达人，更适合联名、搭配拍摄或品牌互推。",
      "recommendedProducts": "Cottage bedding；girls bedroom bedding；floral quilt；crib/toddler room styling",
      "contactInfo": "hello@villagelittleinteriors.com.au",
      "priority": "B+",
      "status": "未联系",
      "isContacted": false,
      "firstContactChannel": "Email",
      "quoteAmount": "",
      "notes": "不是传统达人。先确认是否接受其他品牌床品搭配、联名或摄影合作。",
      "isSelectedForReport": false,
      "isDeleted": false,
      "deletedAt": "",
      "deletionReason": "",
      "images": [],
      "logs": [
        {
          "id": "influencer-20-log-import",
          "actionType": "导入",
          "actionNote": "从 Excel 导入达人主档案",
          "actionDate": "2026-07-09T16:16:31.844826"
        }
      ],
      "createdAt": "2026-07-09T16:16:31.844826",
      "updatedAt": "2026-07-09T16:16:31.844826"
    },
    {
      "id": "influencer-21",
      "platform": "Instagram",
      "accountHandle": "@dfwdorms",
      "displayName": "DFW Dorms | College Dorm Decor & Furniture",
      "profileUrl": "https://www.instagram.com/dfwdorms",
      "country": "Frisco, Texas, USA",
      "followerCount": 53000,
      "followerTier": "Mid-tier",
      "contentType": "Dorm furniture retailer / Dorm design services / Bedding & decor",
      "bioKeywords": "Custom dorm furniture + decor；dorm delivery + nationwide shipping；design services；college essentials",
      "avatarUrl": "",
      "autoFillStatus": "来自 Excel 导入",
      "fitReason": "与 Twin/Twin XL、Back to School、女生宿舍场景高度匹配；但属于零售/设计品牌，可能也是潜在渠道或竞合对象。",
      "recommendedProducts": "Twin/Twin XL bedding；bed skirts；quilts；dorm pillows；back-to-school collection",
      "contactInfo": "support@dfwdorms.com",
      "priority": "A-",
      "status": "未联系",
      "isContacted": false,
      "firstContactChannel": "Email",
      "quoteAmount": "",
      "notes": "优先从渠道合作、Amazon/独立站联盟或宿舍案例搭配切入，不建议按普通寄样达人话术联系。",
      "isSelectedForReport": false,
      "isDeleted": false,
      "deletedAt": "",
      "deletionReason": "",
      "images": [],
      "logs": [
        {
          "id": "influencer-21-log-import",
          "actionType": "导入",
          "actionNote": "从 Excel 导入达人主档案",
          "actionDate": "2026-07-09T16:16:31.844826"
        }
      ],
      "createdAt": "2026-07-09T16:16:31.844826",
      "updatedAt": "2026-07-09T16:16:31.844826"
    },
    {
      "id": "influencer-22",
      "platform": "Instagram",
      "accountHandle": "@campuschickks",
      "displayName": "CampusChickks | Dorm Decor at its Finest",
      "profileUrl": "https://www.instagram.com/campuschickks",
      "country": "美国市场，具体所在地待确认",
      "followerCount": 144000,
      "followerTier": "Mid-tier",
      "contentType": "Dorm inspiration / College lifestyle / Amazon product recommendations",
      "bioKeywords": "Daily dorm inspo；product recommendations；dorm decor tips；shopping guides；move-in tips；Amazon storefront",
      "avatarUrl": "",
      "autoFillStatus": "来自 Excel 导入",
      "fitReason": "内容直接覆盖宿舍床品、收纳、灯具和装饰，受众就是大学女生和家长，是 Brandream Twin/Twin XL 系列的高匹配带货账号。",
      "recommendedProducts": "Twin/Twin XL quilt；dorm duvet cover；bed skirt；throw blanket；back-to-school bedding",
      "contactInfo": "待确认",
      "priority": "A",
      "status": "未联系",
      "isContacted": false,
      "firstContactChannel": "DM；主页/网站联系入口",
      "quoteAmount": "",
      "notes": "优先询问 Amazon storefront、Reel、Story、宿舍购物指南和开学季套餐报价。",
      "isSelectedForReport": false,
      "isDeleted": false,
      "deletedAt": "",
      "deletionReason": "",
      "images": [],
      "logs": [
        {
          "id": "influencer-22-log-import",
          "actionType": "导入",
          "actionNote": "从 Excel 导入达人主档案",
          "actionDate": "2026-07-09T16:16:31.844826"
        }
      ],
      "createdAt": "2026-07-09T16:16:31.844826",
      "updatedAt": "2026-07-09T16:16:31.844826"
    },
    {
      "id": "influencer-23",
      "platform": "Instagram",
      "accountHandle": "@thesmittencollective",
      "displayName": "Krystal Smit | The Smitten Collective",
      "profileUrl": "https://www.instagram.com/thesmittencollective",
      "country": "美国市场，具体所在地待确认",
      "followerCount": 756000,
      "followerTier": "Macro",
      "contentType": "Home finds / Decor / Fashion / Chic everyday living / Amazon & LTK",
      "bioKeywords": "Curated home finds, style & chic everyday living；luxury look for less；Amazon + LTK shopping content",
      "avatarUrl": "",
      "autoFillStatus": "来自 Excel 导入",
      "fitReason": "家居购物和可购买内容能力强，适合独立站或 Amazon 转化；但粉丝体量大，合作成本通常较高。",
      "recommendedProducts": "Elevated bedding；quilt；duvet cover；seasonal bedroom refresh；Amazon home finds",
      "contactInfo": "pstromayer@parkertalentmanagement.com",
      "priority": "B+",
      "status": "未联系",
      "isContacted": false,
      "firstContactChannel": "Talent manager Email",
      "quoteAmount": "",
      "notes": "先索取 media kit、报价、受众地区和平均 Reel 播放，不建议直接寄样。",
      "isSelectedForReport": false,
      "isDeleted": false,
      "deletedAt": "",
      "deletionReason": "",
      "images": [],
      "logs": [
        {
          "id": "influencer-23-log-import",
          "actionType": "导入",
          "actionNote": "从 Excel 导入达人主档案",
          "actionDate": "2026-07-09T16:16:31.844826"
        }
      ],
      "createdAt": "2026-07-09T16:16:31.844826",
      "updatedAt": "2026-07-09T16:16:31.844826"
    },
    {
      "id": "influencer-24",
      "platform": "Instagram",
      "accountHandle": "@annahomecollective",
      "displayName": "Anna Louisa | Anna Home Collective",
      "profileUrl": "https://www.instagram.com/annahomecollective",
      "country": "美国市场可能性高，具体所在地待确认",
      "followerCount": 227000,
      "followerTier": "Macro",
      "contentType": "Budget-friendly home decor / Amazon finds / Everyday styling",
      "bioKeywords": "High-end looks • real-life budgets；Amazon finds + everyday styling；home decor & styling",
      "avatarUrl": "",
      "autoFillStatus": "来自 Excel 导入",
      "fitReason": "预算友好型家居内容和 Amazon 带货属性强，适合 Brandream 的漂亮但价格可接受的床品；已有多次品牌合作经验。",
      "recommendedProducts": "Affordable luxury bedding；neutral quilt；duvet cover；bedroom refresh；Amazon bedding",
      "contactInfo": "待确认",
      "priority": "A-",
      "status": "未联系",
      "isContacted": false,
      "firstContactChannel": "DM；如主页有商务邮箱优先邮箱",
      "quoteAmount": "",
      "notes": "优先询问 Amazon/独立站转化合作和 comment-for-link 形式；先索取报价。",
      "isSelectedForReport": false,
      "isDeleted": false,
      "deletedAt": "",
      "deletionReason": "",
      "images": [],
      "logs": [
        {
          "id": "influencer-24-log-import",
          "actionType": "导入",
          "actionNote": "从 Excel 导入达人主档案",
          "actionDate": "2026-07-09T16:16:31.844826"
        }
      ],
      "createdAt": "2026-07-09T16:16:31.844826",
      "updatedAt": "2026-07-09T16:16:31.844826"
    },
    {
      "id": "influencer-25",
      "platform": "Instagram",
      "accountHandle": "@ourlittlebluehomestead",
      "displayName": "Caitlyn Free",
      "profileUrl": "https://www.instagram.com/ourlittlebluehomestead",
      "country": "USA，州待确认",
      "followerCount": 25000,
      "followerTier": "Micro",
      "contentType": "Small cottage / Homestead / Homemaking / Family lifestyle",
      "bioKeywords": "Small home, big love；900-square-foot cottage；homemaking；backyard homestead；cozy collected home",
      "avatarUrl": "",
      "autoFillStatus": "来自 Excel 导入",
      "fitReason": "粉丝量适中，真实小屋、家庭与温柔乡村生活感很强；非常适合 Brandream 的 cottage、floral 和 cozy bedroom 产品。",
      "recommendedProducts": "Blue floral bedding；cottage quilt；ruffled bedding；bed skirt；family bedroom styling",
      "contactInfo": "待确认",
      "priority": "A",
      "status": "未联系",
      "isContacted": false,
      "firstContactChannel": "DM / Website contact",
      "quoteAmount": "",
      "notes": "首轮可优先联系；建议让她在真实小卧室或 cottage bedroom 中拍摄。",
      "isSelectedForReport": false,
      "isDeleted": false,
      "deletedAt": "",
      "deletionReason": "",
      "images": [],
      "logs": [
        {
          "id": "influencer-25-log-import",
          "actionType": "导入",
          "actionNote": "从 Excel 导入达人主档案",
          "actionDate": "2026-07-09T16:16:31.844826"
        }
      ],
      "createdAt": "2026-07-09T16:16:31.844826",
      "updatedAt": "2026-07-09T16:16:31.844826"
    },
    {
      "id": "influencer-26",
      "platform": "Instagram",
      "accountHandle": "@carlyvandyke_",
      "displayName": "Carly Van Dyke | Style Inspo",
      "profileUrl": "https://www.instagram.com/carlyvandyke_",
      "country": "Florida, USA",
      "followerCount": 127000,
      "followerTier": "Mid-tier",
      "contentType": "Classic / Traditional / Coastal / Grandmillennial home decor",
      "bioKeywords": "Classic style；traditional home decor；coastal home；grandmillennial decor；seasonal styling",
      "avatarUrl": "",
      "autoFillStatus": "来自 Excel 导入",
      "fitReason": "传统、沿海和 grandmillennial 风格与 Brandream 的蓝白花卉、toile、paisley 和浪漫床品高度匹配。",
      "recommendedProducts": "Blue floral duvet cover；toile bedding；paisley bedding；coastal quilt；classic bedroom",
      "contactInfo": "待确认",
      "priority": "A-",
      "status": "未联系",
      "isContacted": false,
      "firstContactChannel": "DM；如主页有邮箱优先邮箱",
      "quoteAmount": "",
      "notes": "先确认报价、卧室内容占比及受众地区；适合经典蓝白或 coastal 产品。",
      "isSelectedForReport": false,
      "isDeleted": false,
      "deletedAt": "",
      "deletionReason": "",
      "images": [],
      "logs": [
        {
          "id": "influencer-26-log-import",
          "actionType": "导入",
          "actionNote": "从 Excel 导入达人主档案",
          "actionDate": "2026-07-09T16:16:31.844826"
        }
      ],
      "createdAt": "2026-07-09T16:16:31.844826",
      "updatedAt": "2026-07-09T16:16:31.844826"
    },
    {
      "id": "influencer-27",
      "platform": "Instagram",
      "accountHandle": "@mytexashouse",
      "displayName": "Erin Vogelpohl | My Texas House",
      "profileUrl": "https://www.instagram.com/mytexashouse",
      "country": "Texas, USA",
      "followerCount": 1000000,
      "followerTier": "Mega",
      "contentType": "Affordable home decor / Modern farmhouse / Walmart product brand",
      "bioKeywords": "Founder and designer of My Texas House collection at Walmart；affordable home decor and fashion",
      "avatarUrl": "",
      "autoFillStatus": "来自 Excel 导入",
      "fitReason": "她拥有 Walmart 独家 My Texas House 家居系列，且该系列覆盖 bedding、pillows 等品类，与 Brandream 存在直接品类竞争。",
      "recommendedProducts": "不建议常规寄样；可用于竞品研究、趋势观察或大型联名评估",
      "contactInfo": "待确认",
      "priority": "C",
      "status": "未联系",
      "isContacted": false,
      "firstContactChannel": "Website / Business contact",
      "quoteAmount": "",
      "notes": "建议放入竞品观察池，而不是首轮达人建联池。",
      "isSelectedForReport": false,
      "isDeleted": false,
      "deletedAt": "",
      "deletionReason": "",
      "images": [],
      "logs": [
        {
          "id": "influencer-27-log-import",
          "actionType": "导入",
          "actionNote": "从 Excel 导入达人主档案",
          "actionDate": "2026-07-09T16:16:31.844826"
        }
      ],
      "createdAt": "2026-07-09T16:16:31.844826",
      "updatedAt": "2026-07-09T16:16:31.844826"
    },
    {
      "id": "influencer-28",
      "platform": "Instagram",
      "accountHandle": "@athomewithjhackie1",
      "displayName": "Jhackleen Boychew",
      "profileUrl": "https://www.instagram.com/athomewithjhackie1",
      "country": "美国市场，具体所在地待确认",
      "followerCount": 1000000,
      "followerTier": "Mega",
      "contentType": "Amazon home finds / Neutral decor / Affordable functional products",
      "bioKeywords": "Amazon Home Finds；Neutral Decor；Affordable • Functional • Worth it；comment-for-link content",
      "avatarUrl": "",
      "autoFillStatus": "来自 Excel 导入",
      "fitReason": "Amazon 家居带货属性强、转化路径成熟；但体量大、内容偏中性简约，合作成本可能较高。",
      "recommendedProducts": "Neutral quilt；cream bedding；white matelassé；affordable bedroom refresh；Amazon bedding",
      "contactInfo": "待确认",
      "priority": "B+",
      "status": "未联系",
      "isContacted": false,
      "firstContactChannel": "Business email / DM",
      "quoteAmount": "",
      "notes": "先索取 media kit、报价、平均播放量及 Amazon 合作方案。",
      "isSelectedForReport": false,
      "isDeleted": false,
      "deletedAt": "",
      "deletionReason": "",
      "images": [],
      "logs": [
        {
          "id": "influencer-28-log-import",
          "actionType": "导入",
          "actionNote": "从 Excel 导入达人主档案",
          "actionDate": "2026-07-09T16:16:31.844826"
        }
      ],
      "createdAt": "2026-07-09T16:16:31.844826",
      "updatedAt": "2026-07-09T16:16:31.844826"
    },
    {
      "id": "influencer-29",
      "platform": "Instagram",
      "accountHandle": "@ruefer.heartandhome",
      "displayName": "Jamie Ruefer",
      "profileUrl": "https://www.instagram.com/ruefer.heartandhome",
      "country": "Tulsa, Oklahoma, USA",
      "followerCount": 211000,
      "followerTier": "Macro",
      "contentType": "Home decor / DIY / Design / Family lifestyle",
      "bioKeywords": "All things home；DIY & DESIGN；faith and family；homebody；shop my home",
      "avatarUrl": "",
      "autoFillStatus": "来自 Excel 导入",
      "fitReason": "真实家庭家居、DIY 和温暖 homebody 调性与 Brandream 的 cozy、farmhouse、cottage 产品匹配。",
      "recommendedProducts": "Farmhouse quilt；floral bedding；cottage duvet cover；seasonal bedroom styling",
      "contactInfo": "待确认",
      "priority": "A-",
      "status": "未联系",
      "isContacted": false,
      "firstContactChannel": "DM；如主页有邮箱优先邮箱",
      "quoteAmount": "",
      "notes": "可重点推荐 farmhouse、green botanical、quilt 系列。",
      "isSelectedForReport": false,
      "isDeleted": false,
      "deletedAt": "",
      "deletionReason": "",
      "images": [],
      "logs": [
        {
          "id": "influencer-29-log-import",
          "actionType": "导入",
          "actionNote": "从 Excel 导入达人主档案",
          "actionDate": "2026-07-09T16:16:31.844826"
        }
      ],
      "createdAt": "2026-07-09T16:16:31.844826",
      "updatedAt": "2026-07-09T16:16:31.844826"
    },
    {
      "id": "influencer-30",
      "platform": "Instagram",
      "accountHandle": "@linenoaksinteriors",
      "displayName": "Synclaire Lawson | Linen Oaks Interiors",
      "profileUrl": "https://www.instagram.com/linenoaksinteriors",
      "country": "美国市场，具体所在地待确认",
      "followerCount": 683000,
      "followerTier": "Macro",
      "contentType": "Home inspiration / Interior decor / Shoppable finds",
      "bioKeywords": "Home inspo；interior decor；comment-for-link shopping content；whimsical and seasonal decor",
      "avatarUrl": "",
      "autoFillStatus": "来自 Excel 导入",
      "fitReason": "家居灵感和可购物内容成熟，适合做卧室焕新和评论自动发链接；但账号体量大，预算要求较高。",
      "recommendedProducts": "Statement quilt；seasonal bedding；floral duvet cover；bedroom refresh",
      "contactInfo": "待确认",
      "priority": "B+",
      "status": "未联系",
      "isContacted": false,
      "firstContactChannel": "Business email / DM",
      "quoteAmount": "",
      "notes": "先询价，不建议直接寄样；确认近期卧室内容和受众年龄。",
      "isSelectedForReport": false,
      "isDeleted": false,
      "deletedAt": "",
      "deletionReason": "",
      "images": [],
      "logs": [
        {
          "id": "influencer-30-log-import",
          "actionType": "导入",
          "actionNote": "从 Excel 导入达人主档案",
          "actionDate": "2026-07-09T16:16:31.844826"
        }
      ],
      "createdAt": "2026-07-09T16:16:31.844826",
      "updatedAt": "2026-07-09T16:16:31.844826"
    },
    {
      "id": "influencer-31",
      "platform": "Instagram",
      "accountHandle": "@sherricalnanhome",
      "displayName": "Sherri Calnan | Coastal Home Styling",
      "profileUrl": "https://www.instagram.com/sherricalnanhome",
      "country": "Falmouth / Cape Cod, Massachusetts, USA",
      "followerCount": 315000,
      "followerTier": "Macro",
      "contentType": "Coastal home styling / High-low decor / California casual / New England charm",
      "bioKeywords": "Timeless high-low home decor；California casual；New England charm；modern coastal design；Amazon + LTK",
      "avatarUrl": "",
      "autoFillStatus": "来自 Excel 导入",
      "fitReason": "沿海与 New England 风格非常适合 Brandream 的 coastal、blue floral、nautical 和清爽白色床品。",
      "recommendedProducts": "Coastal quilt；blue floral duvet cover；white matelassé；nautical bedding；summer bedroom",
      "contactInfo": "联系表单",
      "priority": "A-",
      "status": "未联系",
      "isContacted": false,
      "firstContactChannel": "Website contact / DM",
      "quoteAmount": "",
      "notes": "非常适合 coastal bedding 专项；先询价并查看近期卧室帖表现。",
      "isSelectedForReport": false,
      "isDeleted": false,
      "deletedAt": "",
      "deletionReason": "",
      "images": [],
      "logs": [
        {
          "id": "influencer-31-log-import",
          "actionType": "导入",
          "actionNote": "从 Excel 导入达人主档案",
          "actionDate": "2026-07-09T16:16:31.844826"
        }
      ],
      "createdAt": "2026-07-09T16:16:31.844826",
      "updatedAt": "2026-07-09T16:16:31.844826"
    },
    {
      "id": "influencer-32",
      "platform": "Instagram",
      "accountHandle": "@havrillahome",
      "displayName": "Alli Havrilla",
      "profileUrl": "https://www.instagram.com/havrillahome",
      "country": "美国市场，具体所在地待确认",
      "followerCount": 487000,
      "followerTier": "Macro",
      "contentType": "Amazon home finds / Budget-friendly home decor / Shoppable content",
      "bioKeywords": "Amazon Home Finds；budget-friendly home decor；comment-for-link；affordable finds",
      "avatarUrl": "",
      "autoFillStatus": "来自 Excel 导入",
      "fitReason": "Amazon 带货和评论发链接模式成熟，适合销售导向合作；但账号较大且风格偏大众家居。",
      "recommendedProducts": "Affordable bedding；neutral quilt；pillow covers；bedroom refresh；Amazon bedding",
      "contactInfo": "待确认",
      "priority": "B+",
      "status": "未联系",
      "isContacted": false,
      "firstContactChannel": "Business email / DM",
      "quoteAmount": "",
      "notes": "先询问 Amazon storefront placement、Reel 和 Story 组合报价。",
      "isSelectedForReport": false,
      "isDeleted": false,
      "deletedAt": "",
      "deletionReason": "",
      "images": [],
      "logs": [
        {
          "id": "influencer-32-log-import",
          "actionType": "导入",
          "actionNote": "从 Excel 导入达人主档案",
          "actionDate": "2026-07-09T16:16:31.844826"
        }
      ],
      "createdAt": "2026-07-09T16:16:31.844826",
      "updatedAt": "2026-07-09T16:16:31.844826"
    },
    {
      "id": "influencer-33",
      "platform": "Instagram",
      "accountHandle": "@homeonpinelane",
      "displayName": "Home On Pine Lane",
      "profileUrl": "https://www.instagram.com/homeonpinelane",
      "country": "美国市场，具体所在地待确认",
      "followerCount": 28800,
      "followerTier": "Micro",
      "contentType": "Cozy timeless home decor / Neutral style / Curated finds",
      "bioKeywords": "Cozy, timeless home decor；neutral style；easy styling tips；curated finds",
      "avatarUrl": "",
      "autoFillStatus": "来自 Excel 导入",
      "fitReason": "粉丝量适中、家居定位清晰，适合低成本测试；温柔中性色可匹配 Brandream 的白色、米色和 sage 系列。",
      "recommendedProducts": "Neutral quilt；white bedding；sage bedding；cozy bedroom refresh",
      "contactInfo": "待确认",
      "priority": "A",
      "status": "未联系",
      "isContacted": false,
      "firstContactChannel": "DM；如主页有邮箱优先邮箱",
      "quoteAmount": "",
      "notes": "首轮优先联系；先确认平均 Reels 播放量和是否有卧室场景。",
      "isSelectedForReport": false,
      "isDeleted": false,
      "deletedAt": "",
      "deletionReason": "",
      "images": [],
      "logs": [
        {
          "id": "influencer-33-log-import",
          "actionType": "导入",
          "actionNote": "从 Excel 导入达人主档案",
          "actionDate": "2026-07-09T16:16:31.844826"
        }
      ],
      "createdAt": "2026-07-09T16:16:31.844826",
      "updatedAt": "2026-07-09T16:16:31.844826"
    },
    {
      "id": "influencer-34",
      "platform": "Instagram",
      "accountHandle": "@virgotrendz",
      "displayName": "Vijeta Gupta",
      "profileUrl": "https://www.instagram.com/virgotrendz",
      "country": "Dallas, Texas, USA",
      "followerCount": 517000,
      "followerTier": "Macro",
      "contentType": "Tech / Home / AI / Lifestyle / Fashion / Wellness / Beauty",
      "bioKeywords": "Broad lifestyle creator；tech, home, AI, fashion, wellness and beauty；experienced in gifted partnerships",
      "avatarUrl": "",
      "autoFillStatus": "来自 Excel 导入",
      "fitReason": "有 home 内容和品牌合作经验，但账号主题较宽，家纺受众精准度低于纯家居达人。",
      "recommendedProducts": "Modern bedding；neutral quilt；functional bedroom products；Amazon home finds",
      "contactInfo": "待确认",
      "priority": "B",
      "status": "未联系",
      "isContacted": false,
      "firstContactChannel": "Business email / DM",
      "quoteAmount": "",
      "notes": "仅在预算允许、需要大曝光或产品适合大众 lifestyle 时联系。",
      "isSelectedForReport": false,
      "isDeleted": false,
      "deletedAt": "",
      "deletionReason": "",
      "images": [],
      "logs": [
        {
          "id": "influencer-34-log-import",
          "actionType": "导入",
          "actionNote": "从 Excel 导入达人主档案",
          "actionDate": "2026-07-09T16:16:31.844826"
        }
      ],
      "createdAt": "2026-07-09T16:16:31.844826",
      "updatedAt": "2026-07-09T16:16:31.844826"
    },
    {
      "id": "influencer-35",
      "platform": "Instagram",
      "accountHandle": "@homeinteriortips",
      "displayName": "Laura Nolen",
      "profileUrl": "https://www.instagram.com/homeinteriortips",
      "country": "Colorado, USA",
      "followerCount": 283000,
      "followerTier": "Macro",
      "contentType": "Interior styling tips / Amazon / LTK / Shoppable home decor",
      "bioKeywords": "Interior Styling Tips；Amazon Storefront；LTK；DM for collab；comment-for-link",
      "avatarUrl": "",
      "autoFillStatus": "来自 Excel 导入",
      "fitReason": "专注家居搭配且明确接受合作，Amazon/Link-in-bio 转化路径成熟；适合卧室焕新内容。",
      "recommendedProducts": "Quilt；duvet cover；bedroom styling；neutral bedding；seasonal bedroom refresh",
      "contactInfo": "DM for Collab",
      "priority": "A-",
      "status": "未联系",
      "isContacted": false,
      "firstContactChannel": "DM for Collab / Bio contact",
      "quoteAmount": "",
      "notes": "优先询问卧室 Reel、Story link、Amazon storefront 和内容授权组合价。",
      "isSelectedForReport": false,
      "isDeleted": false,
      "deletedAt": "",
      "deletionReason": "",
      "images": [],
      "logs": [
        {
          "id": "influencer-35-log-import",
          "actionType": "导入",
          "actionNote": "从 Excel 导入达人主档案",
          "actionDate": "2026-07-09T16:16:31.844826"
        }
      ],
      "createdAt": "2026-07-09T16:16:31.844826",
      "updatedAt": "2026-07-09T16:16:31.844826"
    },
    {
      "id": "influencer-36",
      "platform": "Instagram",
      "accountHandle": "@style_meetshome",
      "displayName": "Alisa | Home • Amazon • Lifestyle",
      "profileUrl": "https://www.instagram.com/style_meetshome",
      "country": "美国市场，具体所在地待确认",
      "followerCount": 211000,
      "followerTier": "Macro",
      "contentType": "Home / Amazon / Lifestyle / Coastal and girls-room styling",
      "bioKeywords": "Home • Amazon • Lifestyle；shoppable home content；coastal New England style；girls-room brand partnerships",
      "avatarUrl": "",
      "autoFillStatus": "来自 Excel 导入",
      "fitReason": "既有 Amazon 带货能力，又做过女孩房和沿海家居合作；适合 Brandream 的女生房、coastal 和 romantic bedding。",
      "recommendedProducts": "Girls bedroom bedding；coastal duvet cover；floral quilt；Amazon bedding；dorm-adjacent styling",
      "contactInfo": "alisa.team@emcpower.co",
      "priority": "A-",
      "status": "未联系",
      "isContacted": false,
      "firstContactChannel": "Email",
      "quoteAmount": "",
      "notes": "可优先询问女孩房完整场景合作、Reel + Story + 使用权套餐。",
      "isSelectedForReport": false,
      "isDeleted": false,
      "deletedAt": "",
      "deletionReason": "",
      "images": [],
      "logs": [
        {
          "id": "influencer-36-log-import",
          "actionType": "导入",
          "actionNote": "从 Excel 导入达人主档案",
          "actionDate": "2026-07-09T16:16:31.844826"
        }
      ],
      "createdAt": "2026-07-09T16:16:31.844826",
      "updatedAt": "2026-07-09T16:16:31.844826"
    },
    {
      "id": "influencer-37",
      "platform": "Instagram",
      "accountHandle": "@lafevreliving1",
      "displayName": "LaFevre Living | Home Decor | Lifestyle",
      "profileUrl": "https://www.instagram.com/lafevreliving1",
      "country": "美国市场，具体所在地待确认",
      "followerCount": 20000,
      "followerTier": "Micro",
      "contentType": "UGC creator / Cozy home / Designer-inspired affordable decor",
      "bioKeywords": "UGC Creator；Cozy Home；designer-inspired home decor；easy affordable ideas",
      "avatarUrl": "",
      "autoFillStatus": "来自 Excel 导入",
      "fitReason": "粉丝不大但 UGC 属性明确，适合低成本获得真实家居素材；风格与 Brandream 的漂亮、舒适定位契合。",
      "recommendedProducts": "Neutral bedding；pretty quilt；sage duvet cover；cozy bedroom styling",
      "contactInfo": "待确认",
      "priority": "A",
      "status": "未联系",
      "isContacted": false,
      "firstContactChannel": "DM；如主页有邮箱优先邮箱",
      "quoteAmount": "",
      "notes": "首轮优先；重点询问 1 Reel + 5 photos + raw footage 的 UGC 套餐。",
      "isSelectedForReport": false,
      "isDeleted": false,
      "deletedAt": "",
      "deletionReason": "",
      "images": [],
      "logs": [
        {
          "id": "influencer-37-log-import",
          "actionType": "导入",
          "actionNote": "从 Excel 导入达人主档案",
          "actionDate": "2026-07-09T16:16:31.844826"
        }
      ],
      "createdAt": "2026-07-09T16:16:31.844826",
      "updatedAt": "2026-07-09T16:16:31.844826"
    },
    {
      "id": "influencer-38",
      "platform": "Instagram",
      "accountHandle": "@kinsey_walsh",
      "displayName": "Kinsey Walsh | Home Decor • Design",
      "profileUrl": "https://www.instagram.com/kinsey_walsh",
      "country": "USA，具体所在地待确认",
      "followerCount": 539000,
      "followerTier": "Macro",
      "contentType": "Affordable home decor / Design / Amazon finds / Daily inspiration",
      "bioKeywords": "Affordable home decor + a few splurges；daily finds and inspiration；Amazon affiliate creator",
      "avatarUrl": "",
      "autoFillStatus": "来自 Excel 导入",
      "fitReason": "家居定位强、Amazon 购物影响力较成熟；但体量和合作成本较高。",
      "recommendedProducts": "Affordable luxury bedding；quilt；duvet cover；bedroom refresh；Amazon bedding",
      "contactInfo": "网站联系表单",
      "priority": "B+",
      "status": "未联系",
      "isContacted": false,
      "firstContactChannel": "Website contact / DM",
      "quoteAmount": "",
      "notes": "先获取报价、受众地区、平均播放和 Amazon 转化案例。",
      "isSelectedForReport": false,
      "isDeleted": false,
      "deletedAt": "",
      "deletionReason": "",
      "images": [],
      "logs": [
        {
          "id": "influencer-38-log-import",
          "actionType": "导入",
          "actionNote": "从 Excel 导入达人主档案",
          "actionDate": "2026-07-09T16:16:31.844826"
        }
      ],
      "createdAt": "2026-07-09T16:16:31.844826",
      "updatedAt": "2026-07-09T16:16:31.844826"
    },
    {
      "id": "influencer-39",
      "platform": "Instagram",
      "accountHandle": "@our_sweet_haven",
      "displayName": "MaLoni Doty | Our Sweet Haven",
      "profileUrl": "https://www.instagram.com/our_sweet_haven",
      "country": "美国市场，具体所在地待确认",
      "followerCount": 151000,
      "followerTier": "Macro",
      "contentType": "Home design / Style / Decor / Family lifestyle / Amazon finds",
      "bioKeywords": "Design, style and decor；family with three daughters；comment SHOP；Amazon home and bedroom content",
      "avatarUrl": "",
      "autoFillStatus": "来自 Excel 导入",
      "fitReason": "家庭与女孩房场景潜力强，且已经发布 Amazon bedroom/bedding 内容；适合 Brandream 的 romantic、girls room 和 family bedroom 产品。",
      "recommendedProducts": "Girls bedding；floral duvet cover；quilt；romantic bedroom；Amazon bedding",
      "contactInfo": "待确认",
      "priority": "A-",
      "status": "未联系",
      "isContacted": false,
      "firstContactChannel": "DM；如主页有邮箱优先邮箱",
      "quoteAmount": "",
      "notes": "优先确认卧室帖数据和三位女儿对应的 Twin/Full/Queen 拍摄条件。",
      "isSelectedForReport": false,
      "isDeleted": false,
      "deletedAt": "",
      "deletionReason": "",
      "images": [],
      "logs": [
        {
          "id": "influencer-39-log-import",
          "actionType": "导入",
          "actionNote": "从 Excel 导入达人主档案",
          "actionDate": "2026-07-09T16:16:31.844826"
        }
      ],
      "createdAt": "2026-07-09T16:16:31.844826",
      "updatedAt": "2026-07-09T16:16:31.844826"
    },
    {
      "id": "influencer-40",
      "platform": "Instagram",
      "accountHandle": "@levtexhome",
      "displayName": "Levtex Home",
      "profileUrl": "https://www.instagram.com/levtexhome",
      "country": "Santa Monica, California, USA",
      "followerCount": 31000,
      "followerTier": "Micro",
      "contentType": "Bedding brand / Home décor / Quilts / Comforters / Baby products",
      "bioKeywords": "Elevate your everyday；bedding, décor & home accents；designed in California；shop quilts, duvets, comforters and more",
      "avatarUrl": "",
      "autoFillStatus": "来自 Excel 导入",
      "fitReason": "这是成熟的床品与家居品牌，不是普通达人；产品线与 Brandream 高度重叠，属于直接竞品，更适合做竞品研究、达人反查和内容策略参考。",
      "recommendedProducts": "不建议常规寄样；可研究其 floral、coastal、quilt、kids bedding 与 layered bedding 内容",
      "contactInfo": "待确认",
      "priority": "C",
      "status": "未联系",
      "isContacted": false,
      "firstContactChannel": "Website / Business contact",
      "quoteAmount": "",
      "notes": "建议放入竞品观察池。重点查看其合作达人、被标记内容、季节性卧室布置、Amazon 与独立站导流方式。",
      "isSelectedForReport": false,
      "isDeleted": false,
      "deletedAt": "",
      "deletionReason": "",
      "images": [],
      "logs": [
        {
          "id": "influencer-40-log-import",
          "actionType": "导入",
          "actionNote": "从 Excel 导入达人主档案",
          "actionDate": "2026-07-09T16:16:31.844826"
        }
      ],
      "createdAt": "2026-07-09T16:16:31.844826",
      "updatedAt": "2026-07-09T16:16:31.844826"
    }
  ],
  "brands": [
    {
      "id": "brand-ownkoti",
      "brandName": "Ownkoti",
      "country": "",
      "category": "Home decor / Bedding",
      "priceBand": "Instagram 约92K；Facebook约48K；Pinterest约5.6K，Bedding板块约952条Pin",
      "brandIntro": "彩色、自然、Boho / Cottagecore 的一站式家居用品店",
      "amazonUrl": "",
      "websiteUrl": "https://www.ownkoti.com/pages/about-ownkoti",
      "parentCompany": "",
      "sourceNote": "Brandream_家居床品品牌竞品可视化报告_2026-07.docx",
      "relatedInfluencers": "",
      "notes": "独立站、Instagram、Facebook、Pinterest；Amazon为补充"
    },
    {
      "id": "brand-the-inside",
      "brandName": "The Inside",
      "country": "United States",
      "category": "Designer home / Upholstery",
      "priceBand": "收购公告称此前两年增长近600%；当前单品牌营收未公开",
      "brandIntro": "Pattern-forward 定制软包家具；经典家具结构 + 100多种面料",
      "amazonUrl": "",
      "websiteUrl": "https://www.theinside.com/about-us",
      "parentCompany": "2017年创立；2022年被 Havenly 收购",
      "sourceNote": "Brandream_家居床品品牌竞品可视化报告_2026-07.docx",
      "relatedInfluencers": "",
      "notes": "DTC官网 + Havenly设计服务生态"
    },
    {
      "id": "brand-pottery-barn",
      "brandName": "Pottery Barn",
      "country": "United States",
      "category": "Full-home retail / Bedding",
      "priceBand": "FY2025 Pottery Barn净收入 $2.999B；截至2026-02-01共181家PB门店",
      "brandIntro": "经典美式家居：家具、床品、装饰、户外与完整空间方案",
      "amazonUrl": "",
      "websiteUrl": "https://www.potterybarn.com",
      "parentCompany": "",
      "sourceNote": "Brandream_家居床品品牌竞品可视化报告_2026-07.docx",
      "relatedInfluencers": "",
      "notes": "官网、目录、门店、设计服务、社媒与大型季节活动"
    },
    {
      "id": "brand-evergrace",
      "brandName": "EverGrace",
      "country": "United States",
      "category": "Bedding / Textile",
      "priceBand": "Amazon：10K+订单/近3个月，10K+评分，约4.6星",
      "brandIntro": "以天然棉、TENCEL、Velvet、Faux Fur 等材质系列为核心",
      "amazonUrl": "https://www.amazon.com/EverGrace-Pre-Washed-Lightweight-Bedspread-Oversized/dp/B0G4VGR2T1",
      "websiteUrl": "https://evergracehome.com/",
      "parentCompany": "2018年成立；LinkedIn标注51–200人；纽约第五大道与洛杉矶布局",
      "sourceNote": "Brandream_家居床品品牌竞品可视化报告_2026-07.docx",
      "relatedInfluencers": "",
      "notes": "Amazon、自有官网、批发/家居零售渠道"
    },
    {
      "id": "brand-horimote-home",
      "brandName": "HORIMOTE HOME",
      "country": "",
      "category": "Bedding / Essentials",
      "priceBand": "Amazon：50K+订单/近3个月，50K+评分，约4.5星",
      "brandIntro": "大众价格的素色、轻量、预洗棉与Microfiber quilt/blanket",
      "amazonUrl": "https://www.amazon.com/HORIMOTE-HOME-Pre-Washed-Lightweight-Bedspreads/dp/B0GBSSRCJF",
      "websiteUrl": "https://horimotehome.com/",
      "parentCompany": "商标首次商业使用：2017-10-20；2019年注册",
      "sourceNote": "Brandream_家居床品品牌竞品可视化报告_2026-07.docx",
      "relatedInfluencers": "",
      "notes": ""
    },
    {
      "id": "brand-brandream",
      "brandName": "Brandream",
      "country": "",
      "category": "Bedding",
      "priceBand": "",
      "brandIntro": "",
      "amazonUrl": "https://www.amazon.com/Brandream-Bedding-Woodland-Nursery-Printed/dp/B0CMJYLYB8",
      "websiteUrl": "",
      "parentCompany": "",
      "sourceNote": "Brandream_家居床品品牌竞品可视化报告_2026-07.docx",
      "relatedInfluencers": "",
      "notes": ""
    }
  ]
};
